In [1]:
import pandas as pd

In [2]:
train = pd.read_csv('/kaggle/input/learning-agency-lab-automated-essay-scoring-2/train.csv', index_col='essay_id')
test = pd.read_csv('/kaggle/input/learning-agency-lab-automated-essay-scoring-2/test.csv', index_col='essay_id')

submission = pd.read_csv('/kaggle/input/learning-agency-lab-automated-essay-scoring-2/sample_submission.csv')

In [3]:
train = train.sort_values('score')

# 並べ替え

In [4]:
train

                                                  full_text  score
essay_id
8078135   Venus is called sometimse the evenind ster\n\n...      1
1734068   the author explains his idea to everyone so he...      1
c250ef0   Hello to all who is reading this im wrighting ...      1
c284907   Mars has alot of land forms like cracks,crator...      1
1717119   Can people really show their emotions through ...      1
...                                                     ...    ...
26479a8   After the nice, relaxed weekend at the beach, ...      6
c7a806f   It's FACTS That We Don't Need FACS\n\nBeing in...      6
b8103da   Dear Florida State Senator,\n\nEvery 4 years, ...      6
b5dd327   The Electoral College was created with good in...      6
5aa769f   Technology continues to advance as it becomes ...      6

[17307 rows x 2 columns]

In [5]:
'''

# textBlobを用いて、スペルミスの数を数えます

from textblob import TextBlob
import nltk
# nltk.download('punkt')
nltk.download('wordnet')
train['spelling_errors'] = train['full_text'].apply(lambda x: len(TextBlob(x).correct().words) - len(TextBlob(x).words))

train
'''

"\n\n# textBlobを用いて、スペルミスの数を数えます\n\nfrom textblob import TextBlob\nimport nltk\n# nltk.download('punkt')\nnltk.download('wordnet')\ntrain['spelling_errors'] = train['full_text'].apply(lambda x: len(TextBlob(x).correct().words) - len(TextBlob(x).words))\n\ntrain\n"

In [6]:

# scoreで正規表現からスペルミスの数を比較してみる
train['spelling_errors'] = train.full_text.str.count(r'\b\w{20,}\b')
train['spelling_errors'].groupby(train['score']).mean()

score
1    0.001597
2    0.000635
3    0.000478
4    0.000509
5    0.000000
6    0.000000
Name: spelling_errors, dtype: float64

In [7]:
train

,full_text,score,spelling_errors
essay_id,,,
8078135,Venus is called sometimse the evenind ster\n\n...,1,0
1734068,the author explains his idea to everyone so he...,1,0
c250ef0,Hello to all who is reading this im wrighting ...,1,0
c284907,"Mars has alot of land forms like cracks,crator...",1,0
1717119,Can people really show their emotions through ...,1,0
...,...,...,...
26479a8,"After the nice, relaxed weekend at the beach, ...",6,0
c7a806f,It's FACTS That We Don't Need FACS\n\nBeing in...,6,0
b8103da,"Dear Florida State Senator,\n\nEvery 4 years, ...",6,0
b5dd327,The Electoral College was created with good in...,6,0
5aa769f,Technology continues to advance as it becomes ...,6,0

In [8]:
# test['spelling_errors'] = test['full_text'].apply(lambda x: len(TextBlob(x).correct().words) - len(TextBlob(x).words))

test['spelling_errors'] = test.full_text.str.count(r'\b\w{20,}\b')
test

                                                  full_text  spelling_errors
essay_id
000d118   Many people have car where they live. The thin...                0
000fe60   I am a scientist at NASA that is discussing th...                0
001ab80   People always wish they had the same technolog...                0

In [9]:
# 文章ごとの語の数 
train['word_count'] = train.full_text.str.count(r'\w+')
test['word_count'] = test.full_text.str.count(r'\w+')

train

,full_text,score,spelling_errors,word_count
essay_id,,,,
8078135,Venus is called sometimse the evenind ster\n\n...,1,0,228
1734068,the author explains his idea to everyone so he...,1,0,208
c250ef0,Hello to all who is reading this im wrighting ...,1,0,190
c284907,"Mars has alot of land forms like cracks,crator...",1,0,155
1717119,Can people really show their emotions through ...,1,0,190
...,...,...,...,...
26479a8,"After the nice, relaxed weekend at the beach, ...",6,0,830
c7a806f,It's FACTS That We Don't Need FACS\n\nBeing in...,6,0,645
b8103da,"Dear Florida State Senator,\n\nEvery 4 years, ...",6,0,746
b5dd327,The Electoral College was created with good in...,6,0,709
5aa769f,Technology continues to advance as it becomes ...,6,0,657

In [10]:
# 語の数を比較してみる

train['word_count'].groupby(train['score']).mean()

score
1    271.370607
2    262.381537
3    358.310828
4    481.114875
5    635.847423
6    779.262821
Name: word_count, dtype: float64

In [11]:
# !pip install textstat

In [12]:
'''

import textstat

# Flesch-Kincaid Grade Levelを特徴量として追加する

train['flesch_kincaid_grade'] = train.full_text.apply(textstat.flesch_kincaid_grade)
test['flesch_kincaid_grade'] = test.full_text.apply(textstat.flesch_kincaid_grade)
train
'''

"\n\nimport textstat\n\n# Flesch-Kincaid Grade Levelを特徴量として追加する\n\ntrain['flesch_kincaid_grade'] = train.full_text.apply(textstat.flesch_kincaid_grade)\ntest['flesch_kincaid_grade'] = test.full_text.apply(textstat.flesch_kincaid_grade)\ntrain\n"

In [13]:
# train['flesch_kincaid_grade'].groupby(train['score']).mean()

In [14]:
#!pip install textblob

from textblob import TextBlob

# 感情分析のスコアを特徴量として追加する

train['sentiment'] = train.full_text.apply(lambda x: TextBlob(x).sentiment.polarity)
test['sentiment'] = test.full_text.apply(lambda x: TextBlob(x).sentiment.polarity)

train

,full_text,score,spelling_errors,word_count,sentiment
essay_id,,,,,
8078135,Venus is called sometimse the evenind ster\n\n...,1,0,228,0.163749
1734068,the author explains his idea to everyone so he...,1,0,208,0.184524
c250ef0,Hello to all who is reading this im wrighting ...,1,0,190,-0.002392
c284907,"Mars has alot of land forms like cracks,crator...",1,0,155,0.169592
1717119,Can people really show their emotions through ...,1,0,190,0.001354
...,...,...,...,...,...
26479a8,"After the nice, relaxed weekend at the beach, ...",6,0,830,0.218501
c7a806f,It's FACTS That We Don't Need FACS\n\nBeing in...,6,0,645,0.085178
b8103da,"Dear Florida State Senator,\n\nEvery 4 years, ...",6,0,746,0.107921
b5dd327,The Electoral College was created with good in...,6,0,709,0.171187
5aa769f,Technology continues to advance as it becomes ...,6,0,657,0.133217

In [15]:
'''
!pip install vaderSentiment

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# 感情分析のスコアを特徴量として追加する

analyzer = SentimentIntensityAnalyzer()

train['vader_sentiment'] = train.full_text.apply(lambda x: analyzer.polarity_scores(x)['compound'])

test['vader_sentiment'] = test.full_text.apply(lambda x: analyzer.polarity_scores(x)['compound'])

'''

"\n!pip install vaderSentiment\n\nfrom vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer\n\n# 感情分析のスコアを特徴量として追加する\n\nanalyzer = SentimentIntensityAnalyzer()\n\ntrain['vader_sentiment'] = train.full_text.apply(lambda x: analyzer.polarity_scores(x)['compound'])\n\ntest['vader_sentiment'] = test.full_text.apply(lambda x: analyzer.polarity_scores(x)['compound'])\n\n"

In [16]:
test

,full_text,spelling_errors,word_count,sentiment
essay_id,,,,
000d118,Many people have car where they live. The thin...,0,515,0.179020
000fe60,I am a scientist at NASA that is discussing th...,0,336,0.101786
001ab80,People always wish they had the same technolog...,0,554,0.168435

In [17]:
train

,full_text,score,spelling_errors,word_count,sentiment
essay_id,,,,,
8078135,Venus is called sometimse the evenind ster\n\n...,1,0,228,0.163749
1734068,the author explains his idea to everyone so he...,1,0,208,0.184524
c250ef0,Hello to all who is reading this im wrighting ...,1,0,190,-0.002392
c284907,"Mars has alot of land forms like cracks,crator...",1,0,155,0.169592
1717119,Can people really show their emotions through ...,1,0,190,0.001354
...,...,...,...,...,...
26479a8,"After the nice, relaxed weekend at the beach, ...",6,0,830,0.218501
c7a806f,It's FACTS That We Don't Need FACS\n\nBeing in...,6,0,645,0.085178
b8103da,"Dear Florida State Senator,\n\nEvery 4 years, ...",6,0,746,0.107921
b5dd327,The Electoral College was created with good in...,6,0,709,0.171187
5aa769f,Technology continues to advance as it becomes ...,6,0,657,0.133217

In [18]:
#　スペルミスの割合
train['spelling_errors_rate'] = train['spelling_errors'] / train['word_count']
test['spelling_errors_rate'] = test['spelling_errors'] / test['word_count']

train

,full_text,score,spelling_errors,word_count,sentiment,spelling_errors_rate
essay_id,,,,,,
8078135,Venus is called sometimse the evenind ster\n\n...,1,0,228,0.163749,0.0
1734068,the author explains his idea to everyone so he...,1,0,208,0.184524,0.0
c250ef0,Hello to all who is reading this im wrighting ...,1,0,190,-0.002392,0.0
c284907,"Mars has alot of land forms like cracks,crator...",1,0,155,0.169592,0.0
1717119,Can people really show their emotions through ...,1,0,190,0.001354,0.0
...,...,...,...,...,...,...
26479a8,"After the nice, relaxed weekend at the beach, ...",6,0,830,0.218501,0.0
c7a806f,It's FACTS That We Don't Need FACS\n\nBeing in...,6,0,645,0.085178,0.0
b8103da,"Dear Florida State Senator,\n\nEvery 4 years, ...",6,0,746,0.107921,0.0
b5dd327,The Electoral College was created with good in...,6,0,709,0.171187,0.0
5aa769f,Technology continues to advance as it becomes ...,6,0,657,0.133217,0.0

In [19]:
# スペルミスの割合とスコアの関係を見ます

train[['spelling_errors_rate', 'score']].groupby(train['score']).mean()

       spelling_errors_rate  score
score
1                  0.000008    1.0
2                  0.000003    2.0
3                  0.000001    3.0
4                  0.000001    4.0
5                  0.000000    5.0
6                  0.000000    6.0

In [20]:
# 文章をトークン化する
import nltk

nltk.download('punkt')

from nltk.tokenize import word_tokenize

train['tokens'] = train['full_text'].apply(word_tokenize)
test['tokens'] = test['full_text'].apply(word_tokenize)

# ストップワードを取り除く

nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
train['tokens'] = train['tokens'].apply(lambda x: [word for word in x if word.lower() not in stop_words])
test['tokens'] = test['tokens'].apply(lambda x: [word for word in x if word.lower() not in stop_words])

[nltk_data] Error loading punkt: <urlopen error [Errno -3] Temporary
[nltk_data]     failure in name resolution>
[nltk_data] Error loading stopwords: <urlopen error [Errno -3]
[nltk_data]     Temporary failure in name resolution>

In [21]:
# ストップワードを取り除いた後の語の数を特徴量として追加する

train['word_count_no_stopwords'] = train['tokens'].apply(len)
test['word_count_no_stopwords'] = test['tokens'].apply(len)
train

,full_text,score,spelling_errors,word_count,sentiment,spelling_errors_rate,tokens,word_count_no_stopwords
essay_id,,,,,,,,
8078135,Venus is called sometimse the evenind ster\n\n...,1,0,228,0.163749,0.0,"[Venus, called, sometimse, evenind, ster, brig...",115
1734068,the author explains his idea to everyone so he...,1,0,208,0.184524,0.0,"[author, explains, idea, everyone, help, world...",118
c250ef0,Hello to all who is reading this im wrighting ...,1,0,190,-0.002392,0.0,"[Hello, reading, im, wrighting, today, limting...",97
c284907,"Mars has alot of land forms like cracks,crator...",1,0,155,0.169592,0.0,"[Mars, alot, land, forms, like, cracks, ,, cra...",97
1717119,Can people really show their emotions through ...,1,0,190,0.001354,0.0,"[people, really, show, emotions, computer, ?, ...",142
...,...,...,...,...,...,...,...,...
26479a8,"After the nice, relaxed weekend at the beach, ...",6,0,830,0.218501,0.0,"[nice, ,, relaxed, weekend, beach, ,, Steve, g...",561
c7a806f,It's FACTS That We Don't Need FACS\n\nBeing in...,6,0,645,0.085178,0.0,"['s, FACTS, n't, Need, FACS, school, brings, m...",441
b8103da,"Dear Florida State Senator,\n\nEvery 4 years, ...",6,0,746,0.107921,0.0,"[Dear, Florida, State, Senator, ,, Every, 4, y...",506
b5dd327,The Electoral College was created with good in...,6,0,709,0.171187,0.0,"[Electoral, College, created, good, intentions...",465
5aa769f,Technology continues to advance as it becomes ...,6,0,657,0.133217,0.0,"[Technology, continues, advance, becomes, comp...",447

In [22]:
# ストップワードを取り除いた後の語の数とスコアの関係を見ます

train[['word_count_no_stopwords', 'score']].groupby(train['score']).mean()

       word_count_no_stopwords  score
score
1                   163.769968    1.0
2                   155.618886    2.0
3                   216.414331    3.0
4                   296.381304    4.0
5                   400.121649    5.0
6                   492.705128    6.0

In [23]:
test['word_count_no_stopwords'] = test['tokens'].apply(len)
test

,full_text,spelling_errors,word_count,sentiment,spelling_errors_rate,tokens,word_count_no_stopwords
essay_id,,,,,,,
000d118,Many people have car where they live. The thin...,0,515,0.179020,0.0,"[Many, people, car, live, ., thing, n't, know,...",286
000fe60,I am a scientist at NASA that is discussing th...,0,336,0.101786,0.0,"[scientist, NASA, discussing, ``, face, '', ma...",174
001ab80,People always wish they had the same technolog...,0,554,0.168435,0.0,"[People, always, wish, technology, seen, movie...",328

In [24]:
# 語彙という意味で、tokenを集合にして、数値化したものを特徴量にします

train['vocabulary'] = train['tokens'].apply(set)

test['vocabulary'] = test['tokens'].apply(set)

train


# 語彙の数

train['vocabulary_count'] = train['vocabulary'].apply(len)

train


test['vocabulary_count'] = test['vocabulary'].apply(len)

In [25]:
# scoreが１のものと、６のもので語彙の数を比較してみる

train['vocabulary_count'].groupby(train['score']).mean()

score
1    105.526358
2     96.092949
3    123.289172
4    159.444218
5    205.085567
6    244.717949
Name: vocabulary_count, dtype: float64

In [26]:
train

,full_text,score,spelling_errors,word_count,sentiment,spelling_errors_rate,tokens,word_count_no_stopwords,vocabulary,vocabulary_count
essay_id,,,,,,,,,,
8078135,Venus is called sometimse the evenind ster\n\n...,1,0,228,0.163749,0.0,"[Venus, called, sometimse, evenind, ster, brig...",115,"{corner, includes, nikename, largely, long, ro...",89
1734068,the author explains his idea to everyone so he...,1,0,208,0.184524,0.0,"[author, explains, idea, everyone, help, world...",118,"{penetrate, world, day, acid, sun, cause, know...",73
c250ef0,Hello to all who is reading this im wrighting ...,1,0,190,-0.002392,0.0,"[Hello, reading, im, wrighting, today, limting...",97,"{world, day, reading, saving, next, going, spu...",75
c284907,"Mars has alot of land forms like cracks,crator...",1,0,155,0.169592,0.0,"[Mars, alot, land, forms, like, cracks, ,, cra...",97,"{posible, made, faces, created, know, aliens, ...",72
1717119,Can people really show their emotions through ...,1,0,190,0.001354,0.0,"[people, really, show, emotions, computer, ?, ...",142,"{together, man, fearful, 9, test, long, muscle...",88
...,...,...,...,...,...,...,...,...,...,...
26479a8,"After the nice, relaxed weekend at the beach, ...",6,0,830,0.218501,0.0,"[nice, ,, relaxed, weekend, beach, ,, Steve, g...",561,"{eventually, got, four, replacing, continue, s...",286
c7a806f,It's FACTS That We Don't Need FACS\n\nBeing in...,6,0,645,0.085178,0.0,"['s, FACTS, n't, Need, FACS, school, brings, m...",441,"{shoulders, feel, friend, feelings, Smile, reg...",220
b8103da,"Dear Florida State Senator,\n\nEvery 4 years, ...",6,0,746,0.107921,0.0,"[Dear, Florida, State, Senator, ,, Every, 4, y...",506,"{made, best, definition, immensely, representi...",203
b5dd327,The Electoral College was created with good in...,6,0,709,0.171187,0.0,"[Electoral, College, created, good, intentions...",465,"{heavily, campaigning, elections, feel, quite,...",235
5aa769f,Technology continues to advance as it becomes ...,6,0,657,0.133217,0.0,"[Technology, continues, advance, becomes, comp...",447,"{fearful, instruction, ca, best, right, 9, rec...",234

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(train['score']).astype(int)
y

array([0, 0, 0, ..., 5, 5, 5])

In [28]:
train

,full_text,score,spelling_errors,word_count,sentiment,spelling_errors_rate,tokens,word_count_no_stopwords,vocabulary,vocabulary_count
essay_id,,,,,,,,,,
8078135,Venus is called sometimse the evenind ster\n\n...,1,0,228,0.163749,0.0,"[Venus, called, sometimse, evenind, ster, brig...",115,"{corner, includes, nikename, largely, long, ro...",89
1734068,the author explains his idea to everyone so he...,1,0,208,0.184524,0.0,"[author, explains, idea, everyone, help, world...",118,"{penetrate, world, day, acid, sun, cause, know...",73
c250ef0,Hello to all who is reading this im wrighting ...,1,0,190,-0.002392,0.0,"[Hello, reading, im, wrighting, today, limting...",97,"{world, day, reading, saving, next, going, spu...",75
c284907,"Mars has alot of land forms like cracks,crator...",1,0,155,0.169592,0.0,"[Mars, alot, land, forms, like, cracks, ,, cra...",97,"{posible, made, faces, created, know, aliens, ...",72
1717119,Can people really show their emotions through ...,1,0,190,0.001354,0.0,"[people, really, show, emotions, computer, ?, ...",142,"{together, man, fearful, 9, test, long, muscle...",88
...,...,...,...,...,...,...,...,...,...,...
26479a8,"After the nice, relaxed weekend at the beach, ...",6,0,830,0.218501,0.0,"[nice, ,, relaxed, weekend, beach, ,, Steve, g...",561,"{eventually, got, four, replacing, continue, s...",286
c7a806f,It's FACTS That We Don't Need FACS\n\nBeing in...,6,0,645,0.085178,0.0,"['s, FACTS, n't, Need, FACS, school, brings, m...",441,"{shoulders, feel, friend, feelings, Smile, reg...",220
b8103da,"Dear Florida State Senator,\n\nEvery 4 years, ...",6,0,746,0.107921,0.0,"[Dear, Florida, State, Senator, ,, Every, 4, y...",506,"{made, best, definition, immensely, representi...",203
b5dd327,The Electoral College was created with good in...,6,0,709,0.171187,0.0,"[Electoral, College, created, good, intentions...",465,"{heavily, campaigning, elections, feel, quite,...",235
5aa769f,Technology continues to advance as it becomes ...,6,0,657,0.133217,0.0,"[Technology, continues, advance, becomes, comp...",447,"{fearful, instruction, ca, best, right, 9, rec...",234

In [29]:
train.drop(['full_text', 'tokens', 'vocabulary', 'score'], axis = 1, inplace = True)

In [30]:
type(train)

pandas.core.frame.DataFrame

In [31]:
train

,spelling_errors,word_count,sentiment,spelling_errors_rate,word_count_no_stopwords,vocabulary_count
essay_id,,,,,,
8078135,0,228,0.163749,0.0,115,89
1734068,0,208,0.184524,0.0,118,73
c250ef0,0,190,-0.002392,0.0,97,75
c284907,0,155,0.169592,0.0,97,72
1717119,0,190,0.001354,0.0,142,88
...,...,...,...,...,...,...
26479a8,0,830,0.218501,0.0,561,286
c7a806f,0,645,0.085178,0.0,441,220
b8103da,0,746,0.107921,0.0,506,203
b5dd327,0,709,0.171187,0.0,465,235
5aa769f,0,657,0.133217,0.0,447,234

In [32]:
test

,full_text,spelling_errors,word_count,sentiment,spelling_errors_rate,tokens,word_count_no_stopwords,vocabulary,vocabulary_count
essay_id,,,,,,,,,
000d118,Many people have car where they live. The thin...,0,515,0.179020,0.0,"[Many, people, car, live, ., thing, n't, know,...",286,"{40,000, transports, someone, untile, smoke, '...",185
000fe60,I am a scientist at NASA that is discussing th...,0,336,0.101786,0.0,"[scientist, NASA, discussing, ``, face, '', ma...",174,"{made, unique, saw, relation, beleive, explain...",102
001ab80,People always wish they had the same technolog...,0,554,0.168435,0.0,"[People, always, wish, technology, seen, movie...",328,"{best, eventually, fun, feel, right, test, lon...",173

In [33]:
test.drop(['full_text', 'tokens', 'vocabulary'], axis = 1)

,spelling_errors,word_count,sentiment,spelling_errors_rate,word_count_no_stopwords,vocabulary_count
essay_id,,,,,,
000d118,0,515,0.179020,0.0,286,185
000fe60,0,336,0.101786,0.0,174,102
001ab80,0,554,0.168435,0.0,328,173

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(train,y, shuffle = True)

In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
model_1 = RandomForestClassifier(n_estimators=100, random_state=42)
model_1.fit(train, y)

RandomForestClassifier(random_state=42)

In [37]:
y_pred = model_1.predict(X_valid)
y_pred = le.inverse_transform(y_pred)

In [38]:
# cohen kappa scoreを用いて評価します

from sklearn.metrics import cohen_kappa_score

cohen_kappa_score(y_valid, y_pred, weights='quadratic')

0.6873717424894504

In [39]:
test.drop(['full_text', 'tokens', 'vocabulary'], axis = 1, inplace = True)

In [40]:
test

,spelling_errors,word_count,sentiment,spelling_errors_rate,word_count_no_stopwords,vocabulary_count
essay_id,,,,,,
000d118,0,515,0.179020,0.0,286,185
000fe60,0,336,0.101786,0.0,174,102
001ab80,0,554,0.168435,0.0,328,173

In [41]:
prediction = model_1.predict(test)

In [42]:
pred = le.inverse_transform(prediction)

In [43]:
pred

array([3, 3, 4])

In [44]:
submission['score'] = pred
submission

  essay_id  score
0  000d118      3
1  000fe60      3
2  001ab80      4

In [45]:
submission.to_csv('submission.csv', index = False)